Alternative HTTP server experiments
. Try Simple and Grizzly HTTP servers instead of Jetty
. Modify pre installation script

diff --git a/media-adapter-synology/src/main/scripts/preinst b/media-adapter-synology/src/main/scripts/preinst
--- a/media-adapter-synology/src/main/scripts/preinst
+++ b/media-adapter-synology/src/main/scripts/preinst
@@ -1,6 +1,13 @@
 #!/bin/sh
-if [ ! -f /usr/local/java/bin/java ]; then
-    echo "Could not find Java7+ binary /usr/local/java/bin/java" > $SYNOPKG_TEMP_LOGFILE
+
+if [ -z ${JAVA_HOME} ]; then
+    echo "Java is not configured. JAVA_HOME is not defined." > $SYNOPKG_TEMP_LOGFILE
     exit 1
 fi
+
+if [ ! -f ${JAVA_HOME}/bin/java ]; then
+    echo "Java is not configured. Could not find Java binary." > $SYNOPKG_TEMP_LOGFILE
+    exit 1
+fi
+
 exit 0
